apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mern-kv-provider
  namespace: mern-prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"         # 🔹 Changed from Workload to Managed
    userAssignedIdentityID: ""           # Leave empty if using system-assigned
    keyvaultName: "akskv003883223"
    tenantId: "b5747a39-82cc-4167-ae30-ba662cc41759" # 🔹 Your actual Tenant ID
    objects: |
      array:
        - |
          objectName: mongo-root-username # 🔹 MUST match the name in Azure Portal
          objectType: secret
          objectAlias: username
        - |
          objectName: mongo-root-password # 🔹 MUST match the name in Azure Portal
          objectType: secret
          objectAlias: password
  secretObjects:
    - secretName: mongo-sec
      type: Opaque
      data:
        - objectName: username           # References the objectAlias above
          key: username                  # The key your Pod looks for
        - objectName: password
          key: password
