apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mern-kv-provider
  namespace: mern-prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          # 🔹 Changed to false
    useWorkloadIdentity: "true"            # 🔹 ADDED/Set to true
    keyvaultName: "akskv003883223"
    tenantId: "b5747a39-82cc-4167-ae30-ba662cc41759"
    clientID: "cae19d19-aa14-4606-bcfa-73d52db6ac73" # Ensure this is the ID for aks-kv-identity
    objects: |
      array:
        - |
          objectName: mongo-root-username
          objectType: secret
          objectAlias: username
        - |
          objectName: mongo-root-password
          objectType: secret
          objectAlias: password
  secretObjects:
    - secretName: mongo-sec
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
