apiVersion: v1
kind: ServiceAccount
metadata:
  name: mern-sa
  namespace: mern-prod
  annotations:
    # This connects the K8s account to the Azure Managed Identity
    azure.workload.identity/client-id: "cae19d19-aa14-4606-bcfa-73d52db6ac73"
