apiVersion: v1
kind: ServiceAccount
metadata:
  name: mern-sa
  namespace: mern-prod
  annotations:
    # This connects the K8s account to the Azure Managed Identity
    azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"
