properties([
    parameters([
        string(name: 'Environment', defaultValue: 'dev', description: 'Environment name (dev, staging, prod)'),
        choice(name: 'Terraform_Action', choices: ['plan', 'apply', 'destroy'], description: 'Select the Terraform action to perform')
    ])
])

pipeline {
    agent any

    environment {
        TF_DIR = "infr/"
    }

    stages {
        stage('Preparing & Clean') {
            steps {
                sh "echo Starting Pipeline for ${params.Environment}..."
                deleteDir()
            }
        }

        stage('Git Pulling') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([azureServicePrincipal('meran_stack_sp')]) {
                    sh "terraform -chdir=${env.TF_DIR} init"
                }
            }
        }

        stage('Quality & Security Gates') {
            parallel {
                stage('Format Check') {
                    steps {
                        sh "terraform -chdir=${env.TF_DIR} fmt"
                    }
                }
                stage('Validate Syntax') {
                    steps {
                        sh "terraform -chdir=${env.TF_DIR} validate"
                    }
                }
            }
        }

        stage('Terraform Action') {
            steps {
                withCredentials([azureServicePrincipal('meran_stack_sp')]) {
                    script {
                       // Make sure your .tfvars file is also in the TF_DIR folder!
//                        def varFile = "${params.Environment}.tfvars"

                        if (params.Terraform_Action == 'plan') {
                            sh "terraform -chdir=${env.TF_DIR} plan "
                        }
                        else if (params.Terraform_Action == 'apply') {
                            sh "terraform -chdir=${env.TF_DIR} apply  -auto-approve"
                        }
                        else if (params.Terraform_Action == 'destroy') {
                            sh "terraform -chdir=${env.TF_DIR} destroy  -auto-approve"
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            sh "echo Pipeline execution finished."
        }
        failure {
            sh "echo Pipeline FAILED. Check the security scan or terraform logs."
        }
    }
}